# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  create:
  pull_request_review:
  pull_request:
    branches: [ main ]
    types: [assigned, opened, closed, ready_for_review, review_requested, reopened]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Allows this action to listen for external events
  repository_dispatch:
    types: [createIssue]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
       # We need this extra step to checkout this action as a private repo
      - name: checkout private action
        uses: actions/checkout@v2
        with:
          # This is the actual action we will execute
          repository: EnterpriseDB/edb-actions
          ssh-key: ${{ secrets.SSH_KEY }}
          ref: "main"
          path: .github/actions/edb-actions
        
     # Optional step to verify checkout was successfully executed
      - name: varify
        run: |
          ls -la ./.github/actions/edb-actions

      # This step actuall loads the edb custom action and executes it
      - name: run private action
        uses: ./.github/actions/edb-actions
        with:
          module_id: "github-jira-sync"
          strategy: "unidirectional"
          status_map: '{ "start": "Dev Start", "review": "Dev On Hold", "done": "Dev Done" }'
        env:
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_BASE_URL: "https://edbtest.atlassian.net"
